const hero=document.getElementById('hero'),game=document.getElementById('accepted'),final=document.getElementById('final'),acceptBtn=document.getElementById('acceptBtn'),laterBtn=document.getElementById('laterBtn'),rollBtn=document.getElementById('rollBtn'),dice=document.getElementById('dice'),result=document.getElementById('result'),choice=document.getElementById('choice'),backBtn=document.getElementById('backBtn'),restartBtn=document.getElementById('restartBtn'),toast=document.getElementById('toast'),messageBox=document.getElementById('messageBox'),finalText=document.getElementById('finalText'),copyBtn=document.getElementById('copyBtn'),telegramBtn=document.getElementById('telegramBtn');
let selectedTime='';
const faces=['⚀','⚁','⚂','⚃','⚄','⚅'];
function top(){window.scrollTo({top:0,behavior:'instant'})}
function toastMessage(text){toast.textContent=text;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),3000)}
function face(n){return faces[n-1]}
function makeMessage(time){return `Маша, я в деле 🎲\n\nТогда играем в Катан — ${time.toLowerCase()} ❤️\n\nОстров уже собран. Осталось только встретиться и начать нашу партию.`}
async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch(err){try{const area=document.createElement('textarea');area.value=text;area.setAttribute('readonly','');area.style.position='fixed';area.style.left='-9999px';document.body.appendChild(area);area.select();const ok=document.execCommand('copy');area.remove();return ok}catch(e){return false}}}
function telegramUrl(text){return `https://t.me/share/url?url=&text=${encodeURIComponent(text)}`}
acceptBtn.addEventListener('click',()=>{hero.hidden=true;game.hidden=false;final.hidden=true;top()});
laterBtn.addEventListener('click',()=>{laterBtn.textContent='ЛАДНО, Я ПОДОЖДУ ♡';toastMessage('Хорошо. Но кубики уже приготовлены 🎲')});
rollBtn.addEventListener('click',()=>{if(rollBtn.dataset.rolling==='1')return;rollBtn.dataset.rolling='1';rollBtn.disabled=true;let ticks=0;dice.style.transform='rotate(720deg) scale(1.08)';const timer=setInterval(()=>{dice.textContent=face(Math.floor(Math.random()*6)+1);ticks++;if(ticks>=9){clearInterval(timer);const n=Math.floor(Math.random()*6)+1;dice.textContent=face(n);dice.style.transform='rotate(0) scale(1)';result.innerHTML=`Выпало <strong>${n}</strong>.<br>${n>=4?'Хороший знак. Остров уже на нашей стороне.':'Ничего страшного. Настоящая партия только начинается.'}`;choice.hidden=false;rollBtn.textContent='✓ КУБИК БРОШЕН';rollBtn.dataset.rolling='0';rollBtn.disabled=false}},90)});
document.querySelectorAll('[data-time]').forEach(btn=>btn.addEventListener('click',async()=>{selectedTime=btn.dataset.time;const text=makeMessage(selectedTime);messageBox.textContent=text;finalText.textContent=`Ты выбрала «${selectedTime}». Текст уже скопирован.`;telegramBtn.href=telegramUrl(text);game.hidden=true;final.hidden=false;top();const copied=await copyText(text);if(copied){copyBtn.textContent='✓ СКОПИРОВАНО';toastMessage('Готово — текст скопирован. Теперь нажми «Отправить мне в Telegram».')}else{toastMessage('Автокопирование не сработало. Нажми «Скопировать ещё раз».')}}));
copyBtn.addEventListener('click',async()=>{if(!selectedTime)return;const ok=await copyText(makeMessage(selectedTime));if(ok){copyBtn.textContent='✓ СКОПИРОВАНО';toastMessage('Текст скопирован в буфер обмена 💌')}else toastMessage('Не удалось скопировать. Попробуй ещё раз.')});
telegramBtn.addEventListener('click',()=>{if(selectedTime){telegramBtn.href=telegramUrl(makeMessage(selectedTime));toastMessage('Открываю Telegram…')}});
backBtn.addEventListener('click',()=>{game.hidden=true;hero.hidden=false;top()});
restartBtn.addEventListener('click',()=>{selectedTime='';final.hidden=true;game.hidden=false;choice.hidden=true;result.innerHTML='Нажми на кнопку — кубик решит,<br>с чего начнётся наша партия.';rollBtn.textContent='🎲 БРОСИТЬ КУБИК';rollBtn.disabled=false;rollBtn.dataset.rolling='0';dice.textContent='⚄';top()});