const hero=document.getElementById('hero'),accepted=document.getElementById('accepted'),final=document.getElementById('final'),acceptBtn=document.getElementById('acceptBtn'),laterBtn=document.getElementById('laterBtn'),rollBtn=document.getElementById('rollBtn'),dice=document.getElementById('dice'),result=document.getElementById('result'),choice=document.getElementById('choice'),backBtn=document.getElementById('backBtn'),restartBtn=document.getElementById('restartBtn'),toast=document.getElementById('toast'),messageBox=document.getElementById('messageBox'),finalText=document.getElementById('finalText'),copyBtn=document.getElementById('copyBtn'),telegramBtn=document.getElementById('telegramBtn');
let selectedTime='';
function showToast(text){toast.textContent=text;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2800)}
function top(){window.scrollTo({top:0,behavior:'instant'})}
function diceFace(n){return ['⚀','⚁','⚂','⚃','⚄','⚅'][n-1]}
function invitationText(time){return `Маша, я в деле 🎲\n\nТогда играем в Катан — ${time.toLowerCase()} ❤️\n\nОстров уже собран. Осталось только встретиться и начать нашу партию.`}
async function copyMessage(text){try{await navigator.clipboard.writeText(text);return true}catch(e){const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();const ok=document.execCommand('copy');area.remove();return ok}}
acceptBtn.addEventListener('click',()=>{hero.hidden=true;accepted.hidden=false;top()});
laterBtn.addEventListener('click',()=>{laterBtn.textContent='ЛАДНО, Я ПОДОЖДУ ♡';showToast('Хорошо. Но кубики уже приготовлены 🎲')});
rollBtn.addEventListener('click',()=>{if(rollBtn.dataset.rolling==='1')return;rollBtn.dataset.rolling='1';rollBtn.disabled=true;let ticks=0;dice.style.transform='rotate(720deg) scale(1.12)';const timer=setInterval(()=>{dice.textContent=diceFace(Math.floor(Math.random()*6)+1);ticks++;if(ticks>=9){clearInterval(timer);const n=Math.floor(Math.random()*6)+1;dice.textContent=diceFace(n);dice.style.transform='rotate(0) scale(1)';result.innerHTML=`Выпало <strong>${n}</strong>.<br>${n>=4?'Хороший знак. Остров уже на нашей стороне.':'Ничего страшного. Настоящая партия только начинается.'}`;choice.hidden=false;rollBtn.textContent='🎲 КУБИКИ БРОШЕНЫ';rollBtn.dataset.rolling='0';rollBtn.disabled=false}},95)});
document.querySelectorAll('[data-time]').forEach(btn=>btn.addEventListener('click',async()=>{selectedTime=btn.dataset.time;const text=invitationText(selectedTime);messageBox.textContent=text;finalText.textContent=`Ты выбрала «${selectedTime}». Сообщение уже подготовлено.`;final.hidden=false;accepted.hidden=true;top();const copied=await copyMessage(text);if(copied){copyBtn.textContent='✓ СООБЩЕНИЕ СКОПИРОВАНО';showToast('Готово! Текст скопирован — теперь нажми «Отправить в Telegram» 💌')}else{showToast('Нажми «Скопировать сообщение», чтобы скопировать текст')}telegramBtn.href=`https://t.me/share/url?url=&text=${encodeURIComponent(text)}`}));
copyBtn.addEventListener('click',async()=>{if(!selectedTime)return;const copied=await copyMessage(invitationText(selectedTime));if(copied){copyBtn.textContent='✓ СООБЩЕНИЕ СКОПИРОВАНО';showToast('Скопировано в буфер обмена 💌')}});
telegramBtn.addEventListener('click',()=>{if(!selectedTime)return;const text=invitationText(selectedTime);telegramBtn.href=`https://t.me/share/url?url=&text=${encodeURIComponent(text)}`;showToast('Открываю Telegram…')});
backBtn.addEventListener('click',()=>{accepted.hidden=true;hero.hidden=false;top()});
restartBtn.addEventListener('click',()=>{final.hidden=true;accepted.hidden=false;choice.hidden=true;result.innerHTML='Нажми на кнопку ниже.<br>Пусть остров решит, что будет дальше.';rollBtn.textContent='🎲 БРОСИТЬ КУБИК';top()});
